name: Build and Deploy Blueprint

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install leanblueprint
        run: pip install leanblueprint
      
      - name: Build blueprint
        run: |
          cd blueprint
          leanblueprint web
      
      - name: Deploy to GitHub Pages
        run: |
          cd blueprint/web
          rm -rf .lake declarations/declarations
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A -- ':!.lake'
          git commit -m "Deploy blueprint"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-pages
